### ISSUE TITLE
Feature: Home Page Build Hero section

### ISSUE THREAD

**Issue by brawblan** [Devslopes-Herd/BaseCamp-LandingPage#11]
## Location
- Home page

## Action
- Using HTML and CSS, build the Hero section (inside red outline box)

## Acceptance Criteria
- Matches [Figma Design](https://www.figma.com/file/Pucv53KDfj3qvLtRFWMK2E/HTML-CSS-Landing-Page)
- Meet every action item above.
- I have checked everything in the [Definition of Ready](https://github.com/Devslopes-Herd/TeamStandardsAndRules/blob/main/DefinitionOfReady.md) file.
- Submit a Pull Request

![Hero Section](https://user-images.githubusercontent.com/70041291/184794474-9362a8d0-c098-4e91-bd78-c67f378053d0.png)

**Comment by SamGamgy** [comment]
pushed changes to feature branch

**Comment by mikesz88** [comment]
@SamGamgy, I was so confused by this. This is great that you pushed the changes, but you need to create a pull request for us to merge onto the develop branch.

**Comment by SamGamgy** [comment]
> @SamGamgy, I was so confused by this. This is great that you pushed the changes, but you need to create a pull request for us to merge onto the develop branch.

Oops. Just created the pull request.
