### ISSUE TITLE
Architecture: Create index boilerplate

### ISSUE THREAD

**Issue by mikesz88** [Devslopes-Herd/BaseCamp-LandingPage#3]
## Action
- Create the boilerplate HTML Code in the **main/index.html**

## Acceptance Criteria
- I have created the boilerplate HTML for the main/index.html
- I have checked everything in the [Definition of Ready](https://github.com/Devslopes-Herd/TeamStandardsAndRules/blob/main/DefinitionOfReady.md) file.
- Submit a Pull Request

**Comment by prakhartiwari2507** [comment]
Hey, May I help?

**Comment by Coderuff919** [comment]
Hey @mikesz88, I just deleted all the spaces and push the code back to Github, can you see the changes?

**Comment by mikesz88** [comment]
@Coderuff919 I did! I closed the PR and merged it! :)
