### ISSUE TITLE
Design: Create Assets from Figma

### ISSUE THREAD

**Issue by mikesz88** [Devslopes-Herd/BaseCamp-LandingPage#5]
### You must be a member of the Devslopes-Herd and Devslopes Academy. You may not participate in this repo if you are not a member.

#2 Must be closed before starting this issue

## Action
- Download each image from the [Figma file](https://www.figma.com/file/Pucv53KDfj3qvLtRFWMK2E/HTML%2FCSS-Landing-Page?node-id=0%3A1).
- Name each image according to its location on the Figma file. Example: Downtown_About_Us
- Save each image in an assets folder.

## Acceptance Criteria
- Each image is named correctly and identified.
- The asset folder is created in the root folder. 
- I have checked everything in the [Definition of Ready](https://github.com/Devslopes-Herd/TeamStandardsAndRules/blob/main/DefinitionOfReady.md) file.
- Submit a Pull Request
- Once PR is approved, merge code and delete the branch.
- Mark the issue as complete/done.

**Comment by Coderuff919** [comment]
What file type should we save these images in - SVG, JPEG or PNG?

**Comment by mikesz88** [comment]
@Coderuff919 jpg or png is fine since we are not focused on changing the image color.

**Comment by Coderuff919** [comment]
OK, thanks @mikesz88

**Comment by mikesz88** [comment]
@Coderuff919 Did you take this issue? It is unassigned.

**Comment by Coderuff919** [comment]
Let's see, I want to do my issues first but since that one also needs images, that's why I ask. 
Do the images need to be downloaded on this issue just from the Homepage only or all of the tabs (Homepage to Technology)?

**Comment by mikesz88** [comment]
@Coderuff919 The intention of this issue was for the entire Figma file. But we can revise this issue to just the home since that is what you are working on, and we can create the issues for the rest of the tabs to make it more manageable. You tell me what you want since you have first dibs now.

**Comment by Coderuff919** [comment]
OK, I just do it all, I figure out a way to downloaded multiple images at once. You can assign this to me.

**Comment by Coderuff919** [comment]
How do you want to name duplicate images (the same image is being used on multiple tabs)?

**Comment by Coderuff919** [comment]
<img width="764" alt="Screen Shot 2022-08-18 at 9 18 50 AM" src="https://user-images.githubusercontent.com/29670163/185445326-53d485fd-01fe-489a-857e-cf593e00c760.png">
OK, I will add the number 2 or 3 since some images are used more than twice. 
Also, currently, it is separated into each folder, I figure it easier to find the images. But let me know if you want it all dumped into one big assets folder as the Action said

**Comment by mikesz88** [comment]
That's great thinking! Thank you!
