### ISSUE TITLE
Update Figma Design to match alternative images

### ISSUE THREAD

**Issue by mikesz88** [Devslopes-Herd/BaseCamp-LandingPage#6]
#5 Must be completed before working on this issue

## Action

- Any asset that has the word 'alternative' in the name must replace the original image in the [Figma design](https://www.figma.com/file/0BNiulx6Bm479pJDF9XMYA/Landing-page-Busin-1-(Community)?node-id=1%3A2)

## Acceptance Criteria

- Every image in the asset folder  is appropriately placed in the Figma Design
- I have checked everything in the [Definition of Ready](https://github.com/Devslopes-Herd/TeamStandardsAndRules/blob/main/DefinitionOfReady.md) file.
- Submit a Pull Request
- Once PR is approved, merge code and delete the branch.
- Mark the issue as complete/done.

**Comment by brawblan** [comment]
I am uploading a new Figma File that is 100% editable. You can also grab any image and save it.
